---
title: "Preferential Trade Agreements and Global Value Chains"
author: "Janine De Vera"
date: "`r format(Sys.time(), '%B %d, %Y | %H:%M:%S')`"
output: html_document
---

```{r}
knitr::opts_chunk$set(echo = TRUE,
                      eval = TRUE,
                      error = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      comment = NA)
```

```{r, include=FALSE}
pacman::p_load(tidyverse, readxl, openxlsx, gravity, stargazer, specr, plm,
               modelr, modelsummary, estimatr, haven, scales, knitr, kableExtra,
               grid, gridExtra, patchwork, ggpubr, arrow, vtable, insight)
```

```{r}
setwd("../..")
```


### Baseline Model Dataset:
```{r}
# Baseline dataset for Kazakhstan
df.kaz <- read_parquet("~/Documents/ADB/WTO KAZ/KAZ-gvc-pta/data/02_merged data kazakhstan.parquet") |> 
  mutate(totalGVC = DVA_intrex + FVA + PDC) |> 
  mutate(lnDVA = log(DVA),
         lnDVA_int = ifelse(DVA_int == 0, 0, log(DVA_int)),
         lnDVA_intrex = ifelse(DVA_intrex == 0, 0, log(DVA_intrex)),
         lnFVA = log(FVA),
         lnGVC = log(totalGVC),
         lngdpcap_o = log(gdpcap_o),
         lngdpcap_d = log(gdpcap_d)) |> 
  filter(receive_iso != "KAZ") |> 
  dplyr::rename(year = "year_y") |> 
  #distinct(receive_iso, year, .keep_all= TRUE) |> 
  dplyr::mutate_at(vars(starts_with("depth_")), ~ ifelse(is.na(.), 0, .)) |> 
            mutate(pta = ifelse(is.na(agreement), 0, 1))

# Income group 
income_df <- read_xls("/Users/janinedevera/Documents/ADB/WTO KAZ/02 Data/WB_regions.xls", 
                   skip = 4) |> select(Code, `Income group`) |> 
                   rename(income_class = `Income group`)

# Merge 
df.kaz <- df.kaz |> left_join(income_df, by = c("receive_iso" = "Code")) |> 
  mutate(income_group = ifelse(income_class %in% c("Lower middle income", "Low income"),
                                "low", "high")) |> 
  mutate(income_high = case_when(
    income_group == "high" ~ 1,
    TRUE ~ 0
  ),
  income_low = case_when(
    income_group == "low" ~ 1,
    TRUE ~ 0
  ))

```

### 1. Summary Statistics
```{r}
kaz.stats <- df.kaz |> select(source_iso, receive_name, year, Exports:FVA, totalGVC,
                               depth_wto_plus:depth_econ, gdpcap_d, gdpcap_o, distcap) |> 
             mutate_at(vars(starts_with("depth_")), ~ ifelse(is.na(.), 0, .))

sumtable(kaz.stats,
         vars = c('Exports', 'DVA', 'DVA_int', 'DVA_intrex', 'FVA', 'totalGVC',
                  'depth_wto_plus', 'depth_wto_x', 'depth_total',
                  'depth_core', 'depth_econ', 'gdpcap_d', 'gdpcap_o', 'distcap'),
         summ=c('mean(x)', 'sd(x)', 'min(x)', 'median(x)', 'max(x)'))

```

### 2. Models: FE
```{r}
depvars <- c("lnDVA", "lnDVA_int", "lnDVA_intrex", "lnFVA", "lnGVC")
depvars2 <- c("DVA", "DVA_int", "DVA_intrex", "FVA", "totalGVC")
predictvars <- c("depth_total", "depth_wto_plus", "depth_wto_x", "depth_core", "depth_econ")
covars <- c("lngdpcap_o", "lngdpcap_d", "contig", "comcol", "comlang_off", "distcap", "pta", "income_high") #"eu_d", "gatt_d"
covars_fe <- c(covars, "receive_iso")

# combinations of dep + predict vars
var_list <- list(depvars, predictvars) |> 
  cross() |> 
  map(lift(paste))

combn <- list()
for(i in seq_along(var_list)) {
  combn[[i]] <- var_list[[i]] %>% str_replace(., pattern = " ", " ~ ") %>% unlist()
}

# combinations of dep + predict vars with interaction
predict_list <- map(var_list, ~ str_split(., " ")[[1]][2])
response_list <- map(var_list, ~ str_split(., " ")[[1]][1])

combn_interact <- list()
for(i in seq_along(var_list)) {
  #interaction_wto <- paste0(" + ", predict_list[[i]], ":wto_d", sep = "")
  interaction_term <- paste0(" + ", predict_list[[i]], ":income_high", sep = "")
  #lagged_term <- paste0(" + ", "lag(", response_list[[i]], ", 1)")
  combn_interact[[i]] <- paste0(var_list[[i]] %>% str_replace(., pattern = " ", " ~ "), interaction_term) %>% unlist()
}

# generate linear model formulas
gen_formula <- function(varlist, covars) {
  form <- as.formula(paste0(varlist, " + ",
                            paste0(covars, collapse = "+")))
  form
  }
formulas_list <- map(combn_interact, gen_formula, covars = covars)
formulas_list

# run models
df.panel <- pdata.frame(df.kaz |> select(receive_iso, year, agreement, lnDVA:lnGVC,
                                         depth_wto_plus:depth_econ, lngdpcap_o, lngdpcap_d,
                                         contig, comcol, comlang_off, distcap, pta, 
                                         wto_d, eu_d, gatt_d, income_group, income_high, income_low) |> 
                          filter(!is.na(year)), 
                          index=c("receive_iso", "year"), drop.index=FALSE, row.names=TRUE)

models_list <- map(formulas_list, lm_robust, data = df.panel, se_type = "stata")
models_list_interact <- map(formulas_list, lm_robust, data = df.panel, se_type = "stata")
```

```{r}
modelsummary(models_list[1:3])
```


### 3. Models: FE results
```{r}
models <- c(1:25)

# change models2 to models
models_final <- list()
for (i in seq_along(models)) {
  models_final[[i]] <- models_list_interact[[(models)[i]]]
}

names(models_final) <- paste0("final_model", 1:length(models))
list2env(models_final, .GlobalEnv)

# Regression Results Table (Sample)
broom::tidy(models_list_interact[[5]], statistic = FALSE, conf.int = TRUE, conf.level = 0.90) %>% 
  kable(caption = "Table 1: Regression Results - Model 1", digits = 3) %>% 
  kable_classic(full_width = F, html_font = "Times")
  #add_footnote("n = 1023, adjusted R-squared = 0.52", notation="none")
```

```{r}
modelplot(list(final_model5, final_model6, final_model7, final_model8), draw=FALSE, p.value=TRUE)
```

#### 3.1 Model Plot: Total GVC & Total Depth
```{r}
fig4.3 <- modelplot(final_model5, 
                    coef_omit = "Int",
                    coef_map = c( "depth_total" = "total depth",
                                  "lngdpcap_o" = "GDP capita (orig)",
                                  "lngdpcap_d" = "GDP capita (dest)",
                                  "contig" = "contiguous",
                                  "comcol" = "common colonizer", 
                                  "comlang_off" = "common official language",
                                  "distcap" = "distance between capitals", 
                                  "pta" = "with pta",
                                  "income_high" = "income class (dest)",
                                  "depth_total:income_high" = "total depth x income class"),
                    conf_level = 0.90, linewidth = 0.6,
                    size = 0.8) + 
  aes(color = ifelse(term == "total depth", "depth", "others")) +
  geom_vline(xintercept = 0, size = 0.3, color = "black") + 
  geom_point(aes(y = term, x = estimate), alpha = .3, 
                     size = 5) +
  charts.theme + 
  scale_y_discrete(limits = rev) +
  scale_x_continuous(limits = c(-2,7), breaks = c(-2, 0, 2, 4, 6)) + 
  scale_color_manual(values = c(accent3, main1)) +
  theme(axis.text.x = element_text(size = 10, angle = 0, vjust = 0.5),
        panel.grid.minor.x = element_line(color = "transparent"),
        panel.grid.major.x = element_line(color = "#d4d4d4", linetype = 2),
        panel.grid.major.y = element_line(color = "transparent", linetype = 2),
        plot.subtitle = element_text(size = 10, face = "bold", hjust = 0.5, margin = margin(b = 5)),
        legend.background = element_rect(fill = "transparent", color = "transparent"),
        legend.box.margin = margin(t = 10)) + 
  xlab("coefficients and 95% confidence intervals") + 
  ylab(" ") + 
  guides(color="none")
fig4.3

ggsave(filename="fig4.3.png", plot=fig4.3, device="png", path="../../charts", 
       width = 7, height = 3)
```


#### 3.2 Model Plot: WTO-Plus
```{r}
fig4.4a <- modelplot(list(final_model6, final_model7, final_model8, final_model9, final_model10), 
                        coef_map = c("depth_wto_plus" = ""),
                        conf_level = 0.90, linewidth = 0.6,
                        size = 0.8) + 
 geom_vline(xintercept = 0, size = 0.3, color = "black") + 
 #geom_point(aes(y = term, x = estimate, color = model), alpha = .3, size = 5) +
 charts.theme + 
 #scale_y_discrete(limits = rev) +
 #scale_x_continuous(limits = c(-0.1,0.25), breaks = c(-0.1, 0, 0.1, 0.2)) + 
 scale_x_continuous(limits = c(-0.05,0.15), breaks = c(-0.05, 0, 0.05, 0.1, 0.15)) + 
 scale_color_manual(values = c(main1, main4, accent6, accent2, accent3),
                    labels = c("DVA", "DVA int", "DVA intrex", "FVA", "total GVC")) +
 theme(axis.text.x = element_text(size = 10, angle = 0, vjust = 0.5),
       panel.grid.minor.x = element_line(color = "transparent"),
       panel.grid.major.x = element_line(color = "#d4d4d4", linetype = 2),
       panel.grid.major.y = element_line(color = "transparent", linetype = 2),
       plot.subtitle = element_text(size = 10, face = "bold", hjust = 0.5, margin = margin(b = 5)),
       legend.background = element_rect(fill = "transparent", color = "transparent"),
       legend.box.margin = margin(t = 10)) + 
 xlab(" ") + 
 ylab(" ") + 
 labs(subtitle = "WTO-plus") + 
guides(color=guide_legend(title="dependent variable"))
fig4.4a
```

#### 3.3 Model Plot: WTO-extra
```{r}
fig4.4b <- modelplot(list(final_model11, final_model12, final_model13, final_model14, final_model15), 
                        coef_map = c("depth_wto_x" = ""),
                        conf_level = 0.90, linewidth = 0.6,
                        size = 0.8) + 
 geom_vline(xintercept = 0, size = 0.3, color = "black") + 
 #geom_point(aes(y = term, x = estimate, color = model), alpha = .3, size = 5) +
 charts.theme + 
 #scale_y_discrete(limits = rev) +
 scale_x_continuous(limits = c(-0.05,0.15), breaks = c(-0.05, 0, 0.05, 0.1, 0.15)) + 
 scale_color_manual(values = c(main1, main4, accent6, accent2, accent3),
                    labels = c("DVA", "DVA int", "DVA intrex", "FVA", "total GVC")) +
 theme(axis.text.x = element_text(size = 10, angle = 0, vjust = 0.5),
       panel.grid.minor.x = element_line(color = "transparent"),
       panel.grid.major.x = element_line(color = "#d4d4d4", linetype = 2),
       panel.grid.major.y = element_line(color = "transparent", linetype = 2),
       plot.subtitle = element_text(size = 10, face = "bold", hjust = 0.5, margin = margin(b = 5)),
       legend.background = element_rect(fill = "transparent", color = "transparent"),
       legend.box.margin = margin(t = 10)) + 
 xlab(" ") + 
 ylab(" ") + 
 labs(subtitle = "WTO-extra") + 
 guides(color=guide_legend(title="dependent variable"))
fig4.4b
```

#### 3.4 Model Plot: Core
```{r}
fig4.4c <- modelplot(list(final_model16, final_model17, final_model18, final_model19, final_model20), 
                        coef_map = c("depth_core" = ""),
                        conf_level = 0.90, linewidth = 0.6,
                        size = 0.8) + 
 geom_vline(xintercept = 0, size = 0.3, color = "black") + 
 #geom_point(aes(y = term, x = estimate, color = model), alpha = .3, size = 5) +
 charts.theme + 
 #scale_y_discrete(limits = rev) +
 scale_x_continuous(limits = c(-0.05,0.15), breaks = c(-0.05, 0, 0.05, 0.1, 0.15)) + 
 scale_color_manual(values = c(main1, main4, accent6, accent2, accent3),
                    labels = c("DVA", "DVA int", "DVA intrex", "FVA", "total GVC")) +
 theme(axis.text.x = element_text(size = 10, angle = 0, vjust = 0.5),
       panel.grid.minor.x = element_line(color = "transparent"),
       panel.grid.major.x = element_line(color = "#d4d4d4", linetype = 2),
       panel.grid.major.y = element_line(color = "transparent", linetype = 2),
       plot.subtitle = element_text(size = 10, face = "bold", hjust = 0.5, margin = margin(b = 5)),
       legend.background = element_rect(fill = "transparent", color = "transparent"),
       legend.box.margin = margin(t = 10)) + 
 xlab("coefficients and 90% confidence intervals") + 
 ylab(" ") + 
 labs(subtitle = "core") + 
 guides(color=guide_legend(title="dependent variable"))
fig4.4c
```

#### 3.5 Model Plot: Other Economic
```{r}
fig4.4d <- modelplot(list(final_model21, final_model22, final_model23, final_model24, final_model25), 
                        coef_map = c("depth_econ" = ""),
                        conf_level = 0.90, linewidth = 0.6,
                        size = 0.8) + 
 geom_vline(xintercept = 0, size = 0.3, color = "black") + 
 #geom_point(aes(y = term, x = estimate, color = model), alpha = .3, size = 5) +
 charts.theme + 
 #scale_y_discrete(limits = rev) +
 scale_x_continuous(limits = c(-0.05,0.16), breaks = c(-0.05, 0, 0.05, 0.1, 0.15)) + 
 scale_color_manual(values = c(main1, main4, accent6, accent2, accent3),
                    labels = c("DVA", "DVA int", "DVA intrex", "FVA", "total GVC")) +
 theme(axis.text.x = element_text(size = 10, angle = 0, vjust = 0.5),
       panel.grid.minor.x = element_line(color = "transparent"),
       panel.grid.major.x = element_line(color = "#d4d4d4", linetype = 2),
       panel.grid.major.y = element_line(color = "transparent", linetype = 2),
       plot.subtitle = element_text(size = 10, face = "bold", hjust = 0.5, margin = margin(b = 5)),
       legend.background = element_rect(fill = "transparent", color = "transparent"),
       legend.box.margin = margin(t = 10)) + 
 xlab("coefficients and 90% confidence intervals") + 
 ylab(" ") + 
 labs(subtitle = "other economic") + 
 guides(color=guide_legend(title="dependent variable"))
fig4.4d
```

#### 3.6 Model Plot: All
```{r}
all <- fig4.4a + fig4.4b + fig4.4c +  fig4.4d & theme(legend.position = "bottom")
fig4.4 <- all + plot_layout(guides = "collect")
fig4.4

ggsave(filename="fig4.4.png", plot=fig4.4, device="png", path="../../charts", 
       width = 8, height = 7)
```


### 4. Predictor Variables Comparison
```{r}
response <- map(models_list, find_response)
coeffs <- map(models_list, coef) #%>% 
  #map(function(list){list[predictvars]})

confints <- map(models_list, confint, level = 0.95)
confints <- as.data.frame(do.call(rbind, confints)) |> 
            rownames_to_column(var="variable") |>  
            dplyr::rename(low = `2.5 %`, high = `97.5 %`) |>  
            mutate(variable = gsub("\\..*","",variable))

# dataframe for model coefficients
pred.df <- NULL
model.df <- NULL
for (i in 1:length(coeffs)) {
  x <- data.frame(predictor=names(coeffs[[i]]), coeffs[[i]], row.names=NULL)
  y <- data.frame(rep(i,11), row.names=NULL)
  pred.df <- rbind(pred.df, x)
  model.df <- rbind(model.df, y)
  coeff.df <- cbind(pred.df, model.df)
}

coeff.df <- coeff.df %>% cbind(confints[2:3])
colnames(coeff.df)[2:3] <- c("coefficients", "model")

coeff.df_subset <- coeff.df |> 
  filter(predictor %in% predictvars) |> 
  filter(predictor != "pta") |> 
  mutate(response = unlist(response),
         predictor = fct_relevel(predictor, "depth_total", "depth_wto_plus", "depth_wto_x",
                                 "depth_core", "depth_econ"))
```

#### 4.1 Predictor Comparison
```{r}
fig4.5 <- ggplot(coeff.df_subset |> filter(!(response %in% c("lnDVA", "lnDVA_int"))), 
                   aes(x = coefficients, 
                       y = response)) +
  geom_point(aes(fill = predictor), 
             size = 4.5, 
             shape = 21,
             alpha = 0.9,
             color = "black") +
  #scale_x_continuous(limits = c(0.05, 0.35),
                     #breaks = c(0.1, 0.2, 0.3)) +
  scale_y_discrete(limits = rev, 
                   labels = c("total GVC", "FVA", "DVA intrex", "DVA int", "DVA")) + 
  scale_fill_manual(values = c(accent2, main1, accent6, accent5, accent3),
                    labels = c("total", "wto-plus", "wto-extra", "core", "other economic")) +
  #labs(title = "Effects of PTA Depth on GVC Trade",
       #subtitle = "Structural Gravity Model Estimation Results") +
  xlab("coefficients") + 
  ylab("") +
  charts.theme + 
  theme(axis.text.x = element_text(size = 10, angle = 0, vjust = 0.5),
        panel.grid.major.x = element_line(color = "#d4d4d4", linetype = 2, size = 0.3),
        panel.grid.major.y = element_line(color = "transparent"),
        plot.subtitle = element_text(size = 10, face = "bold", hjust = 0.5, margin = margin(b = 5)),
        legend.box.margin = margin(t = 10),
        legend.spacing.x = unit(0.1, "cm")) + 
  guides(fill=guide_legend(title=" ", override.aes = list(color = "transparent", alpha = 1)))
fig4.5

ggsave(filename="fig4.5.png", plot=fig4.5, device="png", path="../../charts", 
       width = 7, height = 3)
```

### 5. Specification Curve
```{r}
# specification curve analysis
results <- run_specs(df = df.panel, 
                     y = c(depvars), 
                     x = c(predictvars),
                     model = c("lm"),
                     controls = covars)

p1 <- plot_curve(results) +
      charts.theme +
      theme(axis.text.x = element_text(size = 10, angle = 0, vjust = 0.5),
        panel.grid.major.x = element_line(color = "#d4d4d4", linetype = 2, size = 0.3),
        panel.grid.minor.x = element_line(color = "transparent"),
        panel.grid.major.y = element_line(color = "#d4d4d4", linetype = 2, size = 0.3),
        panel.grid.minor.y = element_line(color = "transparent"),
        plot.subtitle = element_text(size = 10, face = "bold", hjust = 0.5, margin = margin(b = 5)),
        legend.box.margin = margin(t = 10),
        legend.spacing.x = unit(0.1, "cm")) + 
      #theme(panel.grid.minor = element_line(color = "transparent")) +
      labs(x = " ", y = "effect of PTA")
           #title = "Specification Curve Analysis",
           #subtitle = "Structural Gravity Model for GVC Trade and PTA Depth")

p2 <- plot_choices(results, choices = c("x", "y", "controls")) +
      labs(x = "model specifications") + 
      charts.theme + 
      theme(axis.text.x = element_text(size = 10, angle = 0, vjust = 0.5),
        panel.grid.major.x = element_line(color = "#d4d4d4", linetype = 2, size = 0.3),
        panel.grid.minor.x = element_line(color = "transparent"),
        panel.grid.major.y = element_line(color = "transparent"),
        plot.subtitle = element_text(size = 10, face = "bold", hjust = 0.5, margin = margin(b = 5)),
        legend.box.margin = margin(t = 10),
        legend.spacing.x = unit(0.1, "cm"),
        strip.background = element_rect(fill = "transparent", color = "transparent"))
      #theme(strip.background = element_rect(fill = "transparent", color = "transparent"),
            #panel.grid.major = element_line(color = "#e0e0e0", linetype = 1, size = 0.2))

fig4.6 <- plot_specs(plot_a = p1,  
                     plot_b = p2,
                     rel_height = c(2, 2))
fig4.6

ggsave(filename="fig4.6.png", plot=fig4.6, device="png", path="../../charts", width = 8, height = 10)
#ggsave("SCA.pdf", spec, device = "pdf", width = 18, height = 15)
```

### 2. Models: PPML
```{r}
# generate combinations of independent variables
combn <- list()
for(i in seq_along(predictvars)) {
  #interaction_term <- paste0(predictvars[[i]], ":wto_d", sep = "")
  combn[[i]] <- c(predictvars[[i]], covars) %>% str_split(., " ") %>% unlist()
}

# generate formulas for all possible combinations of depvars and predictvars
ppml_list <- list()
for (j in seq_along(depvars2)) {
  for(k in seq_along(combn)) {
    temp <- ppml(dependent_variable = depvars2[[j]], distance = "distcap",
                 income_origin = "gdp_o", income_destination = "gdp_d",
                 code_origin = "source_iso", code_destination = "receive_iso",
                 additional_regressors = combn[[k]],
                 robust = T, method = "white1", 
                 #cluster = "distcap",
                 data = df.kaz)
    ppml_list <- c(ppml_list, list(temp))
  }
}
```

```{r}
broom::tidy(ppml_list[[1]], statistic = FALSE, conf.int = TRUE, conf.level = 0.95) %>% 
  kable(caption = "Table 1: Regression Results - Model 1", digits = 3) %>% 
    kable_classic(full_width = F, html_font = "Times")
    #add_footnote("n = 1023, adjusted R-squared = 0.52", notation="none")
```

